---
- name: Install apache server
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: Start and enable autostart of apache server
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Copy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: apache-restart

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: Print web server URL    
  debug:
    msg: "Apache web-server is running at the URL: http://{{ ansible_host }}"

