---
- name: Install apache server
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: Start and enable autostart of apache server
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: Copy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: apache-restart